### ISSUE TITLE
"No compatible source was found for this media" but only on my laptop

### ISSUE THREAD

**Issue by throughglassdarkly** [omarroth/invidious#1040]
I get the error message "no compatible source was found for this media." no matter which video, but only on my laptop that runs the latest Ubuntu. On the linux mint laptop and windows it works fine. 

I very recently installed ubuntu if that has something to do with it. I tried allowing all scripts to run but I can\t figure out what\s wrong?

EDIT> actually this appears to be an issue for all video streaming except youtube. Not an issue with invidious.

**Comment by serpoland** [comment]
It's probably because you don't have codecs installed. Ubuntu offers media codecs package and to install it run these commands.

Add Multiverse repository
`add-apt-repository multiverse`

Update repositories
`apt update`

Install ubuntu media codecs package
`apt install ubuntu-restricted-extras`


https://help.ubuntu.com/community/Repositories/Ubuntu
