### ISSUE TITLE
API - Search By Channel

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [omarroth/invidious#1055]
Could it be possible to add a "authorId" (or a list of "authorId") to the search queries to be able to search videos for a specific channel ?

**Comment by PrestonN** [comment]
You can do this with the following API.

https://github.com/omarroth/invidious/wiki/API#get-apiv1channelssearchucid

**Comment by ZatsuneNoMokou** [comment]
But there's no sort_by and features filters on the one

**Comment by PrestonN** [comment]
It doesn't look like YouTube itself supports filters on channel search, so I'm doubtful that Invidious would support such a feature.

**Comment by ZatsuneNoMokou** [comment]
With YouTube API, you can search videos using a channel id

**Comment by PrestonN** [comment]
Just because the YouTube API provides the functionality doesn't necessarily mean that Invidious can provide it as well. The functionality has to be available on the YouTube website in order for it to be available through Invidious.  This looks to be one of those features that the YouTube site doesn't provide.

**Comment by ZatsuneNoMokou** [comment]
You can get a list in the website with url like `/videos?view=2&flow=grid`

**Comment by omarroth** [comment]
As mentioned I don't expect this is possible currently on the YouTube website, so it is very unlikely to be added. For now if you want search filters when searching channels you'll have to use the YouTube API.
