### ISSUE TITLE
Do Invidious instances accept "personalized" recommendations from YouTube?

### ISSUE THREAD

**Issue by LatterEngineer** [omarroth/invidious#1099]
I'm curious as to where the recommended videos on the homepage of an Invidious YouTube client instance comes from. Is it based on YouTube's algorithm after it's processed all the activity of the instance's users? Is it from the instance administrators? Or is it something else? If it's the first one, what's stopping malcontents from causing the instance to "recommend" offensive videos by watching a ton of them?

Are Invidious instances designed such that Google keeps track of each of them as if they were a user and personalizes recommendations (for videos in the homepage, related videos section, etc) for each of them? Like, (if I recall correctly) if you use YouTube's homepage even if you're not signed in, you'll still get recommendations based on what you watched, and they only go back to the "generl" recommendations if you clear your cookies. If this is the case, I can't help but think that it's really easy for instances to get "infected" with offensive recommendations if certain types of people frequent them. How does Invidious deal with this?

**Comment by omarroth** [comment]
> I'm curious as to where the recommended videos on the homepage of an Invidious YouTube client instance comes from.

The popular page is the most recent videos from the top 40 most subscribed channels on the instance. [This comment](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761) has more information. You can see the code for how it's implemented [here](https://github.com/omarroth/invidious/blob/a2c5211/src/invidious/helpers/jobs.cr#L208-L220).

> Are Invidious instances designed such that Google keeps track of each of them as if they were a user and personalizes recommendations for each of them?

No. Related videos and search results will sometimes differ depending on where the instance is hosted, but otherwise recommendations will match what you get when visiting YouTube after clearing your cookies. Invidious doesn't store any of YouTube's tracking cookies.

**Comment by LatterEngineer** [comment]
Thank you for clearing that up.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by LatterEngineer** [comment]
Thank you for clearing that up.
