### ISSUE TITLE
Add links for genres

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#119]
There are links to channels for each of YouTube "genres" or categories in the descriptions of each video, but they don't work with Invidious, for example:

https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw

https://www.invidio.us/channel/UCYfdidRxbB8Qhf0Nx7ioOYw

**Comment by omarroth** [comment]
I didn't realize those linked to YouTube channels, thank you! Should be a pretty quick fix.

**Comment by dimqua** [comment]
There are non-complete lists:

https://www.youtube.com/feed/guide_builder
https://www.youtube.com/movies

**Comment by omarroth** [comment]
Added with 53732cdcab585da26505a41dcf0d87a36d957502, although it may take a bit for videos to update to include the new URL.

**Comment by dimqua** [comment]
But I don't see any videos, for example https://www.invidio.us/channel/UCiDF_uaU1V00dAc8ddKvNxA

**Comment by omarroth** [comment]
Right. Genre channels are an edge case, as they link to videos but don't have any themselves (notice that the /videos page is empty). I'd probably open a new issue for that.

**Comment by omarroth** [comment]
Added some extra handling for genre channels with 5632e58636d09d56a12006b8879771aef90ae504. For some reason YouTube will happily provide URLs to non-existent channels. For example, http://invidio.us/watch?v=lRfdMiURV4s provides an invalid URL for Education - Topic. RSS feeds for genre channels also don't work (on YouTube at least, Invidious seems to be able to handle them). The only other problem I found was with the [News - Topic](https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw channel, because it only links to livestreams, so the `/videos` tab is empty.

That's about all I have to mention, feel free to open a new issue for genre channels if some of them don't work.
