### ISSUE TITLE
Single user instance blocked

### ISSUE THREAD

**Issue by nelimee** [omarroth/invidious#1228]
Hi everyone!
I just got my personal, self-hosted invidious instance blocked by Google, the infamous "Could not extract video info. Instance is likely blocked.".
A `wget` on any random youtube URL gives a `ERROR 429: Too Many Requests.`.

I checked that I was the only one to access my instance in https://my.instance.xx/api/v1/stats and it is the case, I am the only one using the instance.

I though that the blocked instances were shared instances with a lot of users and connexions. Have you heard of other small instances being blocked?

**Comment by cloudrac3r** [comment]
I've heard of that happening occasionally. Couple of things to check:

- Is your instance exposed to the public internet?
- Do you have request logs that you can use to verify that you're the only one sending requests?
- Do you run any other YouTube downloaders on that IP address? All requests to YouTube from any application from your IP address count towards the request limit.

**Comment by iAmNoVa-UXX** [comment]
I found if you just reload it a few times it usually works.

**Comment by nelimee** [comment]
Hi,

- My instance is exposed to the public internet yes. But neither the main domain nor the subdomain have ever been exposed to anyone.
- I did not set anything more than the Docker image. If any request log is included by default in invidious then I probably have this without knowing it. I may have also my nginx logs, I will have a look.
- Nope, no other access to YouTube from this IP address, only the invidious instance.

> I found if you just reload it a few times it usually works.

I just re-tried and invidious is working again. Seems like waiting a few hours fix the issue, I will close and add some information if the issue come back later.

Thank you both for your answers :)

**Comment by cloudrac3r** [comment]
> Seems like waiting a few hours fix the issue

YouTube releases blocks automatically after a few hours/days. This is always the case.

> I may have also my nginx logs, I will have a look.

Please check those if you can.

> I found if you just reload it a few times it usually works.

This likely only applies to invidio.us, not selfhosts. This is almost certainly not relevant here.

> My instance is exposed to the public internet yes. But neither the main domain nor the subdomain have ever been exposed to anyone.

There are some bots — and I have been affected by one — that look around the internet for Invidious instances and similar software and use them to scrape content from YouTube instead of accessing YouTube directly. These bots do not require a link to the instance, I think they just scan the whole internet or something.

You should also check https://instances.invidio.us in case someone else has listed you without you knowing.

The request logs will answer whether you are being hit by bots or users that you are unaware of.

If none of the above apply, perhaps there is some interesting new blocking behaviour to look into.

**Comment by nelimee** [comment]
I just checked and do have *a few* suspicious IPs that comes up, but it is really not significant.
```
docker logs --since 48h nginx-proxy | grep -e "my.instance.me" | wc -l
```
outputs `23702` whereas
```
docker logs --since 48h nginx-proxy | grep -e "my.instance.me" | grep -v "[my IP]"
```
only shows `8` accesses from `2` different IPs (I will check them afterwards).

My instance is not listed on the public list of instances you linked.

**Comment by cloudrac3r** [comment]
Okay, 8 accesses is not a big deal. I guess either you watched a LOT of videos (~1000 in 24 hours) by yourself, or there's some restrictions that we don't know about yet.
