### ISSUE TITLE
How do i fix this and do i need to host my own version of the website and if so how?

### ISSUE THREAD

**Issue by IdotMaster1** [omarroth/invidious#1238]
![IMG_0003 1](https://user-images.githubusercontent.com/48019206/84603282-77b20a80-ae8d-11ea-8c21-3cc45c9b2aad.PNG)

**Comment by SuperSandro2000** [comment]
Use a browser that is not obsolete.

**Comment by IdotMaster1** [comment]
i cant is there a way to fix it by hosting my own server

**Comment by SuperSandro2000** [comment]
> i cant

Then I think you are probably on your own.

You would need to transpile the js to an older ecma version. Not sure if it would work because your browser might be that old that it can't understand everything invidious tries to do even with polyfills. Most definitely it would be slower and probably wouldn't run on your phone.

**Comment by omarroth** [comment]
This is an issue with Google login, not JS. See #754.

**Comment by IdotMaster1** [comment]
i don't even get to login i don't even press the button

**Comment by devomaa** [comment]
Thats your browser.
