### ISSUE TITLE
subscriptions - mark videos as read

### ISSUE THREAD

**Issue by Ingwersaft** [omarroth/invidious#129]
hi, first of all: awesome project!

one feature would be really awesome for me: mark videos as watched right on the invidious subscription feed. 
maybe a small icon on top of a video preview, only visible when hovering the image

**Comment by omarroth** [comment]
Thank you! You can already hide watched videos in your feed by checking `Only show unseen` in your preferences, if that does what you want. 

Otherwise, I would be fine marking watched videos throughout the site. Only when hovering over seems like it would make it difficult to see, but I'd be curious about other thoughts on this.

**Comment by Ingwersaft** [comment]
Yeah I know that, but I want to hide videos without clicking on them and then forwarding till the end :)

The hover idea was only a suggestion to prevent visual clutter, but you're right, that might make such a feature rather hard to find.

**Comment by omarroth** [comment]
Actually, just clicking on a video will mark it as watched. As for an indicator, maybe a grey filter over the thumbnail?

**Comment by Ingwersaft** [comment]
Ah, didn't notice that. So I can open all videos I like to mark as watched in new tab and then just close them. That's nearly as convenient as my mark-as-watched button idea 👍 

Ah, are you talking about an indicator to show if a video has been watched already. Maybe a red progress bar like youtube does? Maybe [checked_circle outlined](https://material.io/tools/icons/?icon=check_circle&style=outline) for unwatched and [check_circle filled](https://material.io/tools/icons/?icon=check_circle&style=baseline) for beeing watched?

This logo could even be a toggle to switch between watched and unwatched states

**Comment by omarroth** [comment]
That's personally what I do, although I think it could be more convenient. 

Watched/unwatched videos are pretty binary, so a progress bar doesn't make as much sense for Invidious as it does for YouTube. 

I like the ability to toggle watched as an alternative to clearing your watch history. Invidious uses https://ionicons.com/, so you might take a look there to see if there's anything there that would be a good fit, I don't see anything currenlty.

**Comment by Ingwersaft** [comment]
I like the `radio-button-off` for unwatched and `checkmark-circle-outline` for watched.

**Comment by dimqua** [comment]
What about `eye` and  `eye-off`

**Comment by omarroth** [comment]
Added with 6b12f11. I'll probably add some extra behavior for users with different subscription settings, since currently it will hide the video, even if the user has `unseen_only` set to `false`.

6b12f11 also adds `/feed/history` which does the opposite, see #182.

**Comment by omarroth** [comment]
Currently the option to mark videos as `watched` only appears when the user has `only show unwatched` enabled in their preferences, since it doesn't much since otherwise as videos will reappear on a refresh.

I think I'll close this since the requested functionality has been implemented. If there are any issues or suggestions for improving this, I'd be happy to discuss them in a new issue.

**Comment by elypter** [comment]
>Currently the option to mark videos as watched only appears when the user has only show unwatched enabled in their preferences, since it doesn't much since otherwise as videos will reappear on a refresh.

why not just mark the videos with these settings?

**Comment by omarroth** [comment]
I'm not quite sure what you mean. The reason that option isn't available unless `only show unwatched` is enabled is generally because it's extremely confusing to mark a video as watched only to have it show up when you refresh your feed.

**Comment by elypter** [comment]
why cant it work just like with links in the browser that turn purple if you visited them. no need to make them disappear if the user disabled it.

**Comment by omarroth** [comment]
I think you might misunderstand the original issue, which was about this functionality:
![mark_watched](https://user-images.githubusercontent.com/14208607/51077594-6e0bee00-166e-11e9-9b70-72a0697bb01a.gif)
(the cursor is in the incorrect place because of the recording software, it's clicking the eye).

This extends the functionality of the feed, and makes what @Ingwersaft was trying to do quite a bit easier, see [this](https://github.com/omarroth/invidious/issues/129#issuecomment-415759012) comment above.

**Comment by utlasidyo** [comment]
There was grey filter over watched video's thumbnails? Why is was removed? I don't want watched videos to be completely hidden from my feed.

**Comment by omarroth** [comment]
> yeah, but why not keep the eye symbol in the disabled setting as well and cross out the eye if the video was hidden

I'm not quite sure what you're asking here. Is this similar to what @utlasidyo is requesting?

> Please add grey filter over thumbnails of watched videos, I don't want them to be completely hidden from my feed.

Mind opening this as a new issue?
