### ISSUE TITLE
Youtube comments suggestion

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#132]
You can make youtube comments on the site look more youtube-like by placing the publishing date and the number of likes to the bottom of users comments.
This is an example from SkyTube app: ![](https://i.imgur.com/kY6kVqI.png)

And probably there is no need for +/- buttons, at least for YouTube comments.

**Comment by omarroth** [comment]
Looks good!

**Comment by omarroth** [comment]
Added with 650b44a.

**Comment by Jtasiu** [comment]
>Added with 650b44a
@omarroth I think this made comments stop showing anymore whenever JS is disabled. Is there some way to still show comments when JS is off like it was before?

**Comment by omarroth** [comment]
Reddit comments have used JS since c7a46cd, and YouTube comments have used JS since they were added with  1eb7066. The reason why is because comments were the largest source of latency for loading the `/watch` page, adding about 3 seconds, so they were split off into a separate request.

It might be possible to try to reintegrate them back into the initial page load, but obviously it would reintroduce that issue. You also wouldn't be able to view replies to comments, or minimize YouTube or Reddit comments, since that functionality also uses JS.

If you'd like to download comments for offline viewing or for use in another application, you can with `/api/v1/comments/:videoID`. [Here](http://invidio.us/api/v1/comments/cvFH_6DNRCY)'s an example, and more info is available about that [here](https://github.com/omarroth/invidious/wiki/API#get-apiv1commentsid).

I think it's unfortunate that JS is necessary, and obviously I would prefer that it wasn't (the way it was originally), but I hope I was able to explain why it currently works the way it does, sorry I couldn't be more help.

**Comment by Jtasiu** [comment]
I see. Is the latency a problem for the user or the server? If it's on user side I think those with JS off wouldn't mind a few extra seconds. If you can somehow show comments back in the initial page load that would be amazing it was a great feature. I could also view replies to comments even when JS was off. Would noscript tags be able to do something here? Or some way to have comments in initial page load if JS off is detected and the way it is now if JS is detected on?

**Comment by dimqua** [comment]
> those with JS off wouldn't mind a few extra seconds

+1
