### ISSUE TITLE
Cookie sharing

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#136]
The cookie used by http://www.invidio.us should also be usable by http://invidio.us.

**Comment by omarroth** [comment]
The reason this is taking so long is because I opted into [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) a while back, which unfortunately prevents redirecting through the DNS/Registrar, since they would need a valid HTTPS certificate for the site. It's just a case of adding a handler for redirecting to a specified host, I was just waiting on it in the hopes that the HSTS would expire and I could do it through DNS/Registrar.

**Comment by elypter** [comment]
dont forget dev.invidio.us

**Comment by omarroth** [comment]
Added with bf867c3fcf347b3425b52ecd1da8850d2526199b. I expect `www.` to redirect to the root in the future (as per my previous comment). But the same cookie should now work on all subdomains.

You'll have to log out and sign in again to get the updated cookie.
