### ISSUE TITLE
Browser extensions to replace YouTube links with

### ISSUE THREAD

**Issue by neomodern** [omarroth/invidious#157]
To make Invidious more usable it would help to redirect YouTube links to Invidious. 

There's already a [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/hooktube-redirect/)
 which redirects YouTube links to Invidious. 

[This old Hooktube extension](https://addons.mozilla.org/en-US/firefox/addon/hooktube/) used to
 replace embedded YouTube videos, so it could be the basis for an Invidious extension.

**Comment by omarroth** [comment]
Take a look [here](https://github.com/omarroth/invidious#extensions). There should already be an extension linked there that does what you want.

**Comment by omarroth** [comment]
I'd take a look at [Invidious Redirect](https://greasyfork.org/en/scripts/370461-invidious-redirect) for an extension that should work. 

If I misread the original issue: With #115, #134,  #135 links to YouTube should **automatically** be changed to the equivalent Invidious links (in comments and description), and will remove tracking from external links. If there is a place where that is not the case, I'd recommend opening a new issue for that. I think I'll probably close this due to inactivity. Feel free to reopen if I'm missing anything.
