### ISSUE TITLE
Error pages for 500/504/etc.

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#176]
(Moved from #173)

The site currently doesn't have proper error pages for most errors.
I think instead of the raw HTTP codes/one-liners, it should give a bit of explanation:
   - for 503/504 one that would explain that the servers are overloaded
   - for 500 one that would point them to make an issue here
   - etc etc.

I know some errors (like 404) do have their own pages, but I think all but the worst errors should be caught before the user sees them.

**Comment by omarroth** [comment]
Proposed errors:

For 503/504: Unfortunately this is an error provided by the host, I don't think there's much I can do to change it.
For 500,other fatal errors: `Looks like you've found a bug in Invidious. Feel free to open an issue [here](github.com/omarroth/invidious) or send an email to omarroth@protonmail.com`
For 404: YouTube actually redirects to `/`  instead of showing `404`, I'd be open to doing that instead

I think most errors are caught before the user sees them, although sometimes an error can crop up where I didn't expect it, so there's no handling for it. I think those are getting fewer, as I've tried to make errors non-fatal (leaving a video out of search if Invidious can't extract info from it for example, or leaving channels empty instead of `500`).

**Comment by omarroth** [comment]
Added proposed error messages with dfd17bdd8823cf0b1d9d7e1287371d236f406ada.
