### ISSUE TITLE
Invidio.us embed doesn't allow clicking through to Invidio.us when Google domains blocked

### ISSUE THREAD

**Issue by ajvsol** [omarroth/invidious#177]
If you block youtube.com and googlevideo.com domains then you get just a picture reading "The media could not be loaded, either because the server or network failed or because the format is not supported."
![](https://i.imgur.com/FjAD5Ol.png)

There's no way to click through to watch the video on Invidio.us and right-clicking the video doesn't bring up any additional options either.

**Comment by omarroth** [comment]
Hi! The reason why that's happening is likely because it's trying to load

**Comment by Jtasiu** [comment]
>With #34 the videos will be proxied through Invidious so this won't be an issue

That sound amazing @omarroth! Is it really possible without too much bandwidth costs?

**Comment by omarroth** [comment]
Well, that remains to be seen. Currently thumbnails don't add that much extra cost, but they're much smaller. I think in the coming week I'll probably push experimental 1080p to registered users, and then site-wide depending on bandwidth usage.

**Comment by dimqua** [comment]
Is it REALLY necessary to proxy 1080p videos to have a support of them? After all, youtube-dl doesn't proxy anything.

**Comment by omarroth** [comment]
There's more info [here](https://github.com/omarroth/invidious/issues/5#issuecomment-405093857), but to paraphrase: because of the way 1080p+ videos are packaged, it is very preferable to use something like [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) to combine the audio and video streams. DASH has some other technical requirements that can only be met by proxying the video files. Sorry for the somewhat round-about answer, but I have looked into this quite a bit and I think that proxying files is the solution in this case. Obviously the increased bandwidth usage is not ideal.

The reason youtube-dl doesn't proxy anything because it has full control over the requests it makes and how the files are combined. When in the browser, you have to work with/around [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), which makes it difficult to directly request files from googlevideo.com (when they are provided seperately).

@PrestonN provides a good explanation [here](https://github.com/FreeTubeApp/FreeTube/issues/60#issuecomment-379130798).
There's also an explanation by @cloudrac3r [here](https://github.com/cloudrac3r/cadencegq/issues/2#issuecomment-407580663).

Short answer is yes, it is necessary. :)

**Comment by dimqua** [comment]
Hmm, isn't linked @cloudrac3r's comment means that he already found a some sort of solution for this issue?

**Comment by omarroth** [comment]
Yes, @cloudrac3r's solution is to sync the audio and video manually. That is also the solution that @PrestonN considers in his linked comment as well. The problem with syncing it manually is that it gets very messy very quickly. Keeping audio and video in sync when quality changes, speed changes, among other things makes it difficult to pull off.

**Comment by cloudrac3r** [comment]
I haven't found a situation where I *haven't* been able to play 1080p+, and more often that not it works without an issue, but there are times when I have to fiddle with the pause button to hear sound or to get it to synchronise properly.

Proxying videos on Invidious was already a requested feature — using that to play DASH videos the proper way is obviously the best move.

**Comment by omarroth** [comment]
You can currently view videos without connecting Google domains by enabling `Proxy videos?` in your preferences or by setting `default quality` to `dash`, so I'm going to close this.

**Comment by ajvsol** [comment]
This doesn't appear to work for _embedded_ videos (e.g. using the [Invidious Embed](https://addons.mozilla.org/en-GB/firefox/addon/hooktube-embed) extension) without googlevideo.com also being allowed. Videos viewed through invidio.us directly however seem to be proxied fully.

**Comment by omarroth** [comment]
You may have to clarify what you mean. User preferences are not used when watching an embedded video, but adding `local=true` as I mentioned appears to work as expected, example: https://invidio.us/embed/aqz-KE-bpKQ?local=true . 

I'm not opposed to using user preferences in embeds. I'd recommend opening a new issue for that to further discussion.

**Comment by ajvsol** [comment]
Ah I thought it was still related to the original issue since embeds still don't work fully but I can open a new issue.
