### ISSUE TITLE
Some feature suggests

### ISSUE THREAD

**Issue by Jtasiu** [omarroth/invidious#178]
Thank you this project @omarroth it is great. I love that almost everything is proxied locally and it works well without JS. I have a few suggests

1 - Is it possible to get filters to sort by like in search results, sort by newest comments as well as most viewed/least viewed filters in channels like what is on youtube?
2 - Can get the duration of the video in the thumbnail?
3 - Can get option to add one-click search option for browsers like firefox?

thank you for your great work

**Comment by omarroth** [comment]
I'm happy that everything is working well!
- Search filters are already implemented, although not documented, I'd take a look at #126 for how they work, but as a quick example  `sort:views type:channel CHANEL` will do the search you mentioned. Comment filters are tracked in #101.
- All the pieces necessary for this one are already implemented, expect it to be added soon.
- You might take a look at the extensions on the [README](https://github.com/omarroth/invidious#extensions) to see if there's already an extension that does what you want. Otherwise, you may have to add some more info for this.

**Comment by Jtasiu** [comment]
Thanks for reply and great to see them implemented.

By one-click search (Opensearch) option I mean the ones you can add to your browser so you can search the site directly from browser address or search bar. When you visit a website like youtube which supports it you can click address bar or search bar to add an option to search straight from the bar. You can also see https://mycroftproject.com/youtube-search-plugins.html for more examples

**Comment by omarroth** [comment]
I think I'll close this in favor of #205 and #202. Feel free to open a new issue if you have any other suggestions.
