### ISSUE TITLE
Watch history

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#182]
Currently there is no way to see your list of watched videos, e.g. https://www.youtube.com/feed/history.

**Comment by omarroth** [comment]
This is actually a bit of a limitation in how Invidious keeps watch history. As you can see [here](https://github.com/omarroth/invidious/blob/master/src/invidious/users.cr#L25), Invidious currently stores watch history just as a list of video IDs, which is enough to filter results, but not enough to display a list of videos. A couple things will have to be changed to support this, just thought I'd provide some info.

**Comment by omarroth** [comment]
Added with 6b12f11. Currently, since Invidious only stores watch history as a list of video IDs, the only relevant information that can be displayed is the thumbnail. Expect this to be updated to support `title` and `length_seconds`. I'd be open to adding more information, the only concern is space.

Currently `/feed/history` is not linked to from anywhere. I'll probably add a link in `/preferences`, and maybe add it as a tab once #227 is added, although I'd appreciate thoughts on this.

**Comment by cloudrac3r** [comment]
I don't think the eye icon makes sense as a button to clear a video from the history — a delete icon like an x or a garbage can would make more sense.

Linking to the history in the settings sounds sensible. You could also add a link at the top of /feed/subscriptions, next to the "Manage subscriptions" link perhaps.

**Comment by dimqua** [comment]
> I'd be open to adding more information, the only concern is space.

Well, the publisher name and date would be nice to have.

**Comment by omarroth** [comment]
I'm going to close this since the original functionality has already been implemented.

I'm looking into refactoring to allow for the publisher name and date, as well as some other information, which should be tracked in #259, so expect to see that added soon.
