### ISSUE TITLE
Direct link to video files

### ISSUE THREAD

**Issue by gitbugged** [omarroth/invidious#20]
It should be possible to link directly to videos which would allow users to open them from their favorite video player. Multiple formats preferred (like low res or audio only), but not required.

**Comment by omarroth** [comment]
Maybe adding a `&raw=1` option to `/embed/:id` params?

As for multiple formats, maybe having a `&quality=` option, where the quality can be one of the options described in #9.

For embedded videos, you can also enable audio only by adding `&listen=true`.

**Comment by omarroth** [comment]
What is an example of a video player that would be used with this feature?

**Comment by Zero3K** [comment]
MPC-BE

**Comment by omarroth** [comment]
I unfortunately cannot test with MPC-BE, but VLC has a similar feature, which works with ac8fb9d. For embedded videos, a user can specify `&quality=:q` where `:q` is `hd720`,`medium`,`small`. Adding `&raw=1` will redirect to the specified video.

For example:
```
https://invidio.us/embed/SACeGmvxE1A?raw=1&quality=medium
```
Will redirect to the video file with `medium` quality, if it exists. Otherwise, it will redirect to the `hd720` file.

**Comment by Zero3K** [comment]
It works with MPC-BE. It would be nice if the file name would show up as the name of the video instead of the url.

**Comment by Zero3K** [comment]
What issues?

**Comment by omarroth** [comment]
Essentially the only way (to my knowledge) to get around the problem I mentioned is to proxy the file and modify headers so that it will work properly. This is fine, but it's much more bandwidth intensive.

That's currently the main issue.
