### ISSUE TITLE
instagram

### ISSUE THREAD

**Issue by ChloeMackey** [omarroth/invidious#203]
Not sure if this is the right place to ask, but how hard would it be to create an invidious for instagram? A private front end to subscribe to public profiles.

**Comment by omarroth** [comment]
I recently came across [Webstagram](https://web.stagram.com/), which might be what you want. Otherwise if someone else would like to pick this up, I would be happy to provide any assistance on the [FreeTube Matrix Server](https://riot.im/app/#/room/#freetube:matrix.org).

Answering how hard it would be: that would depend on how much the site in question tries to prevent it. Netflix or example, uses Widevine DRM to prevent sharing and downloading of their content.

I think I'll close this for now, if you or anyone has similar questions that aren't related directly to functionality in Invidious, feel free to ask them [here](https://riot.im/app/#/room/#freetube:matrix.org).
