### ISSUE TITLE
500 Server Error.

### ISSUE THREAD

**Issue by shortenjukebox** [omarroth/invidious#215]

**Comment by omarroth** [comment]
Take a look now to see if it's working for you.

**Comment by dotdapple** [comment]
Works now!

**Comment by shortenjukebox** [comment]
I’ve been getting the error again, unfortunately.

**Comment by omarroth** [comment]
Unfortunately you'll have to provide more details. Is it happening on every page or just your subscriptions?

**Comment by shortenjukebox** [comment]
Sorry for the terseness: it was on every page.

Just rebooted my computer and I was able to access the front page, though I start getting the error again after attempting to log in.

**Comment by omarroth** [comment]
Strange. My guess might be that some invalid data snuck into your account, an invalid cookie or similar, but I'm not quite sure what the issue is, and I can't find anything that might indicate a problem.

Would you mind providing your user id? You can email me privately at omarroth@protonmail.com if you don't want to post it here.

**Comment by omarroth** [comment]
The issue was determined to be a non-existent account that still had open sessions. Session ids should now be cleared properly when an account is deleted with f647f7bdea7f92d9ca9cee279cc1f58421165c88, but I'm not sure why the account in question was removed.

If anyone else encounters this issue please get in touch. It's concerning and I can't see any reason why it should occur, unless of course a user removes their account.
