### ISSUE TITLE
Infinite Captcha tries

### ISSUE THREAD

**Issue by Avizini** [omarroth/invidious#239]
I filled the captcha wrongly and invidio.us took me to an error page from there I simply clicked back button and I was presented with the same captcha.

I don't know if this is an issue, if it isn't then close this.

**Comment by omarroth** [comment]
Big issue, thank you very, very much. Should be fixed with d185ba84bf3dff26ed715ad6f318d26af0192fd5.

**Comment by Avizini** [comment]
You're welcome. I accidently discovered this!

**Comment by omarroth** [comment]
It's identical to the one used [Tutanota](https://app.tutanota.com/). The user is correct that the possibility space is quite small, and although I won't go in depth on how to exploit it, it is fairly weak.

I expect it to change pretty soon to something with a much larger possibility space, and I think I'll open a new issue for proposing alternatives, since I already have one in mind that I would appreciate thoughts on.
