### ISSUE TITLE
Fix player size

### ISSUE THREAD

**Issue by Emaro** [omarroth/invidious#243]
Fix the player size to display the whole video with no need for scrolling. Currently I even have to use the mouse with the scrollbar, since one "scroll" with the mouse wheel moves the top of the player out of the viewport.

I've a 4k monitor. Maybe only large screens are affected.

Before scrolling
![Without scrolling the bottom of the player is cut off](https://user-images.githubusercontent.com/25137789/48673433-b2cd4a00-eb41-11e8-9d91-7e6d3f652bcf.png)

After scrolling with the mouse wheel
![After scrolling with the mouse, the top is cut off](https://user-images.githubusercontent.com/25137789/48673443-c973a100-eb41-11e8-9df8-5d1550910cbe.png)

**Comment by omarroth** [comment]
See also #4 and #33. Design is obviously not my strength. I'll probably just add a `max-size` for larger screens, but I'd like to hear @dimqua 's thoughts on this.

**Comment by zipline808** [comment]
I like the minimalistic approach to the design, I always felt like YouTube was trying to squish too much stuff in front of my eyes. It was quite oxymoronic in that way; its design elements were simplistic but the design itself seemed noisy. I don't feel distracted by other stuff while watching a video on Invidious.

I would suggest having three modes for the player: normal and maximised, which are both self-explanatory, and fill. In fill mode the player will resize itself so that it consumes as much space as it can without exceeding the boundary of *screenspace minus navbar minus padding*. I think this a little over-the-top but maybe even a custom mode where the user can manually resize the video by dragging at a corner of the player, and the custom size will be persistent provided the user has an account to store his preferences.

**Comment by omarroth** [comment]
I'm going to consider this fixed with a283c3143d3707dabc3b225d50d600b022c4965f, although if it is still an issue I'll be happy to re-open. I'd like to open @zipline808 's suggestions as a new issue, since they're interesting and I think a separate issue would help discussion.

**Comment by kampka** [comment]
I feel this issue still is still valid for 8f41130

**Comment by omarroth** [comment]
Would you mind providing a little more information on why this is still an issue? If you could provide e.g. screenshot and browser used so it's easier to address.

**Comment by kampka** [comment]
Sure thing. The browser used is Firefox, but Chromium behaves the same.
As you can see in the screenshot, the player stretches out of the screen on the bottom end.
You have to scroll to get the controlls and you cannot get the video to fit the screen unless you shrink the browsers window size.

![invidio us](https://user-images.githubusercontent.com/422412/54140158-4c877280-4423-11e9-9487-2e190c2f6407.png)

**Comment by omarroth** [comment]
Gotcha. Should be fixed with 19c32bf993d7909c91c2b511c4e32610148b1109.

**Comment by kampka** [comment]
Looking good, thanks a lot!

**Comment by Emaro** [comment]
It works for me too. Thanks!
