### ISSUE TITLE
Add support for Safari's picture-in-picture mode

### ISSUE THREAD

**Issue by tonilampela** [omarroth/invidious#252]
With Safari there is currently no way to enter browser's native picture-in-picture mode for Invidio.us videos. PiP mode works with nearly every other video player on web, including official YouTube.com, so it would be nice to see invidio.us to also support it.

**Comment by omarroth** [comment]
Unfortunately I'm not able to test with Safari. Using Chrome, there is a "View in-picture mode" that appears to work as expected, and Firefox Nightly appears to support it by enabling `media.videocontrols.picture-in-picture.enabled` in `about:config`.

Since there hasn't been any follow-up I'm going to close this. Feel free to open a new issue or leave a comment here and I'll be happy to re-open.
