### ISSUE TITLE
No video supported format and MIME type found while using Tor Browser Bundle 

### ISSUE THREAD

**Issue by TNTBOMBOM** [omarroth/invidious#261]
Hi There, 

it seems to be that there is some issue with invidious while been visited from TBB. 

e.g: 

http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion/watch?v=HP_qouNbTEg

![invidious](https://user-images.githubusercontent.com/11895339/49575955-ed095a80-f93b-11e8-9fea-3d7dc7fb5668.png)

Thx!

**Comment by omarroth** [comment]
You might check to see if NoScript is blocking the video links. Also see #150 and #151.

**Comment by TNTBOMBOM** [comment]
But it was working before without the need of allowing JS in order to watch the video. (i need to allow JS of googlevideos in order to watch the video)

**Comment by omarroth** [comment]
Invidious currently relies on googlevideos to serve the files themselves (it doesn't serve any JS). If you'd like Invidious to proxy the files, you can set your `preferred quality` to `dash`, as mentioned in #185.

**Comment by its3ch0** [comment]
> But it was working before without the need of allowing JS in order to watch the video. (Now i need to allow JS of googlevideos in order to watch the video)

NoScript also blocks media by default.

**Comment by omarroth** [comment]
As mentioned above, NoScript blocks media by default, which is likely causing this issue. With `Security Settings` set to `safest` I am able to watch videos through Invidious with media enabled.

By default Invidious the player links to googlevideo.com, although the videos can be proxied by adding `&local=true` to the `/watch` url, or by enabling `Proxy videos?` in your preferences.

Since there hasn't been any follow up I'm going to close this. If there are still any problems feel free to open a new issue or leave a comment here and I'll be happy to re-open.
