### ISSUE TITLE
[Suggestion] When autoplay next video is selected the next video should start automatically

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#268]
Instead of just loading the next video it should also automatically played even if this is not activated in the settings because it would be mostly pointless otherwise. The same with playlists if the previous video ended due to playing to the end.

**Comment by omarroth** [comment]
It can also be used to queue up the next video without automatically starting. 

Generally, I think it's better to respect the user's settings rather than assuming that whatever the user is doing is pointless and try to prevent it.

**Comment by elypter** [comment]
i dont want to prevent users from doing what they want. i just think that for those who use this function they mostly want to use it to have an automated background entertainment. this is currently not possible unless you enable autoplay globally which is annoying if you restart your browser or if you click a lot of video links in a forum at once but dont want them play all at the same time.

**Comment by LoveIsGrief** [comment]
I can't even find where to autostart videos. Simply loading the next page and not playing the video is useless to me. I could do the 2 clicks myself.

In any case, a simple workaround is to get GreaseMonkey or another addon and add this script
```javascript
// ==UserScript==
// @name     Autoplay Invidio.us
// @include  https://www.invidio.us/*
// @version  1
// @grant    none
// @run-at document-end
// ==/UserScript==

let interval = setInterval( () => {
  if(!unsafeWindow.videojs){
   	return; 
  }
  unsafeWindow.videojs("#player").play() && clearInterval(interval);
}, 200);
```

**Comment by omarroth** [comment]
You can enable autoplay by adding `&autoplay=1` to the end of the URL, or by enabling `autoplay` in https://invidio.us/preferences. If autoplay is enabled when watching a video, it will "carry over" to the next video.

In this case I see two options:
- Default to autoplay when viewing playlist/etc (even when autoplay is disabled globally)
- Requiring user to add an extra option (mentioned above) or enable autoplay

My thought here is that user preferences should be respected when possible, so I would prefer the first option, unfortunately making this a `wontfix`. If there's some other option I haven't considered please mention it, otherwise I'm going to close this.

**Comment by LoveIsGrief** [comment]
# /preferences

I didn't know the preferences page existed and only saw the cogwheel icon when suspecting it existed. I'd therefore suggest either:

 - writing "preferences"
 - increasing the cogwheel icon size
 - changing the location of the cogwheel to somewhere more obvious.

It doesn't really jump out / it isn't obvious. This most likely would go into a different issue.

# Autoplay

## Wording

I'd change the wording from "Autoplay next video" to "Auto**load** next video" or something similar, since it really isn't playing the next video. If you do leave the wording, then imo it really should autoplay and not just load the next page. Or make it dependent on the setting, but write what it really does.

## Respecting user preference

If you're uncomfortable with adding an additional option on the video page to override the preference for the upcoming videos, then at least let the user know that it's possible to change the preference e.g add a "*" and a hover-text stating as much.

It's just that as a user, I got frustrated that I:

 1. Couldn't find out how to autoplay stuff
 2. Ticked "autoplay" and it didn't autoplay

In any case, thanks a lot for the effort you've put into this. I don't mean to sound aggressive.

**Comment by omarroth** [comment]
Maybe a "Autoplay when viewing playlist" option? That could then be on by default but still allow people who wanted to use it as a "queue

**Comment by omarroth** [comment]
Added with bb5a1ad5136d9c85dd89def312921ae61bd4f856.
