### ISSUE TITLE
504 Gateway Time-out when importing subscriptions from `subscription_manager`

### ISSUE THREAD

**Issue by android4682** [omarroth/invidious#269]
I've tried different browsers but I keep getting the following error (after awhile):
```
504 Gateway Time-out
The server didn't respond in time.
```

Is there any other way of getting my subscriptions imported easily?

**Comment by its3ch0** [comment]
I got the same issue when I initially signed up. Can confirm it happens over here is well.

**Comment by omarroth** [comment]
Sometimes when a user has a large number of subscriptions, importing all of them takes long enough to cause the load balancer to timeout and return a 504. I'm looking into replacing the load balancer because of this, among other reasons, but for now there isn't much I can do here.

Trying to import multiple times should eventually work, but you might try running something like this in the console (on the `/data_control` page).
```javascript
var subscriptions = [
  "UCl2mFZoRqjw_ELax4Yisf6w",
  "UCXuqSBlHAE6Xw-yeJA0Tunw",
  //...
];

for (i = 0; i < subscriptions.length; i++) {
  var xhr = new XMLHttpRequest();
  xhr.responseType = "json";
  xhr.timeout = 20000;
  xhr.withCredentials = true;

  xhr.open("GET", "/subscription_ajax?action_create_subscription_to_channel=1&c=" + subscriptions[i], true);
  xhr.send();
}
```

That does the same job as if you were clicking the `subscribe` button for each of the channels listed in `subscriptions`.

Sorry that I can't be more help here, once the load balancer is replaced I expect problems like this to go away.

**Comment by android4682** [comment]
Fair enough. Thanks!

**Comment by omarroth** [comment]
Just pushed c2c224b16f9ee11e5bebeed8901aedbc0e15bfae, which should help speed up importing. For users that are having trouble signing in with Google, I would recommend trying again now.
