### ISSUE TITLE
Reload videos when they were inactive for too long - mitigation for "a media error occured"

### ISSUE THREAD

**Issue by Wittmaxi** [omarroth/invidious#276]
When a video is left inactive for a long time, it really should reload before the source expires. Additionally, make it reload with the timestamp. 

This is relevant because I usually leave my Computer On overnight for various reasons and in the morning, I am usually facing a "media error occured" after a few minutes of music.

**Comment by omarroth** [comment]
Since I haven't had a chance to push out a fix for this yet I thought I'd try to provide some explanation as to the problem.

YouTube provides video links that are only valid for 6 hours. So when leaving the page open for longer they expire and return an error. The expected fix is to replace them with a redirect that will always point to a valid copy. The only concern now is that it may cause additional latency in load time, but expect this to be mitigated soon.

**Comment by Wittmaxi** [comment]
Additional latency in load time isn't necessary (and would be extremely bad, given the current load time). Instead, you could just add a ```<meta http-equiv="refresh" content="<timerequiredfor6h>">

**Comment by omarroth** [comment]
I should have clarified. Additional latency refers to loading the video itself, which would have to redirect at least once. googlevideo.com already appears to do multiple redirects, so I don't expect it to be as much of a concern.

**Comment by Wittmaxi** [comment]
oh okay

**Comment by omarroth** [comment]
Pushed out a9aae6b36c270643461a80b9987ed611077498af, which should mitigate this. Obviously it's difficult to test, since the issue only appears after several hours. videojs should automatically retry sources on error, but if it this is still an issue I'll close this in favor of #236.

**Comment by omarroth** [comment]
I've encountered and safely recovered from this issue several times, so I'm ready to call this one fixed. If the player encounters an error, it will now try to recover every 5 seconds (to prevent flickering).

Feel free to open a new issue if it is still a problem for you.
