### ISSUE TITLE
What happened to kgg2m7yk5aybusll.onion?

### ISSUE THREAD

**Issue by leonklingele** [omarroth/invidious#280]
What happened to the ~official~ hidden service of this repo (kgg2m7yk5aybusll.onion), was it replaced by https://invidio.us?

**Comment by omarroth** [comment]
No. I'm afraid I've been having with it recently and I've received another question about it as well. Unfortunately, the issue appears to be with the Tor daemon, and I'm currently investigating it.

I've restarted it, and it appears to be working currently.

**Comment by leonklingele** [comment]
Down again :(

**Comment by leonklingele** [comment]
For anyone else in need, I've set up two hidden services (v3, v2) which act as a reverse proxy for https://invidio.us/:

- http://fz253lmuao3strwbfbmx46yu7acac2jz27iwtorgmbqlkurlclmancad.onion/
- http://qklhadlycap4cnod.onion/

Please don't use it for anything you don't want me to read.

**Comment by omarroth** [comment]
Great! You might consider adding them to the list of public instances [here](https://github.com/omarroth/invidious/wiki/Invidious-Instances).

**Comment by omarroth** [comment]
I'm going to close this since there are now four public onion services that people can use:

- http://kgg2m7yk5aybusll.onion/
- http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion/
- http://qklhadlycap4cnod.onion/
- http://fz253lmuao3strwbfbmx46yu7acac2jz27iwtorgmbqlkurlclmancad.onion/

Thank you @leonklingele. 

If there are any issues with the official instances, please feel free to open a new issue.
