### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by mrtargaryen** [omarroth/invidious#281]
I discovered invidio.us and its exactly what I'm looking for, however, I want to register but the "register" link is greyed out. How am I able to register?

**Comment by omarroth** [comment]
That's a confusing part of the UI, the "Login/Register" button is grayed out because you're on that page (as compared to the "Login with Google"). At the bottom you can see:
![image](https://user-images.githubusercontent.com/14208607/50983990-542fa700-14c6-11e9-9610-f0b069cde202.png)

Which will let you do what you want.

**Comment by mrtargaryen** [comment]
> That's a confusing part of the UI, the "Login/Register" button is grayed out because you're on that page (as compared to the "Login with Google"). At the bottom you can see:
> ![image](https://user-images.githubusercontent.com/14208607/50984150-c1433c80-14c6-11e9-8320-1b0d8ef650a0.png)
> 
> Which will let you do what you want.

I should have looked a little more closely, thank you very much :)
