### ISSUE TITLE
Security: Use random password while creating "kemal" user

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#298]
At the moment the database user has always the same password if you do not change it in setup.sh and config manually. It should be some random string for better security.

**Comment by omarroth** [comment]
Generally, I would expect an administrator to change the password to something they think is more appropriate rather than relying on the script to do it automatically. 

That also appears to be the expectation [here](https://github.com/sergiotapia/magnetissimo/blob/master/config/dev.exs#L35-L43), and [here](https://github.com/vjpr/live-bootstrap/blob/03dc970796eaf268f9ec8d8039a899a3a95b0aad/app/config/database.coffee#54), although I'm quite sure there are other projects with similar defaults. Additionally, postgres does not allow users outside of the localhost to connect by default.

I don't think this is much of a security concern. I would expect that if someone made their database public facing, they would be able to change the default password.

**Comment by Perflyst** [comment]
You know how lazy people are. The readme tells them to execute setup.sh and they copy & paste. We shouldn't relay on that someone knows what he does.
Using default passwords is and always was a security issue. Best example are all these public facing NAS' or routers in the internet with default passwords.

**Comment by omarroth** [comment]
Fair enough. As I mentioned though, an administrator would have to make an effort to make themselves vulnerable, assuming they were using the default `pg_hba.conf`.

**Comment by Perflyst** [comment]
Some admins are lazy, some do copy&paste, some don't know what they do. But yeah, lets close it.

wontfix
