### ISSUE TITLE
Some videos don't have audio streams

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#333]
Ex: https://www.youtube.com/watch?v=NXeclBNp0Q8

This is an old low-quality video, and apparently it doesn't have an audio-only stream.

In Listen mode, the player is frozen without a Play button, although DASH works without issues.  
It should either load a video track that has audio, redirect to the video mode, or show some kind of error.

**Comment by omarroth** [comment]
DASH must be falling back on another source, since the manifest for the above video appears to be empty. You can see the available sources [here](https://invidio.us/api/v1/videos/NXeclBNp0Q8?pretty=1).

I think a redirect would likely be most appropriate if a video has no available audio sources, although I think it's a little jarring. I understand that this is an edge case though, so I don't have a problem doing that if the issue isn't very common.

**Comment by omarroth** [comment]
Added redirect with 0cf86974dd840137ac5202acc0919f5d0a8ff3c2.

**Comment by Discookie** [comment]
Would it be possible to force a non-DASH quality in the redirect, since DASH also prevents playing the video?

**Comment by omarroth** [comment]
Added with 744cc25339f4eca1d86bf82d31094a035266bcf2.

**Comment by ubone** [comment]
erroneous bug: the example video in the first post does have audio only stream
