### ISSUE TITLE
[feature] Copy video link

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#39]
Can you please add a possibility to copy a link of the currently playing video using invidious's video player? 

It's useful for embeded videos. Probably, you can add "Share this video" button or something to copy a link to youtube.com and/or invidio.us.

**Comment by xKeiro** [comment]
And if you were to implement this please also include time stamp support!

**Comment by omarroth** [comment]
Think I'll probably do something like how YT shortens URLs, so you can link to videos like `invidio.us/:id`. @xKeiro, I'm assuming you mean like `&t=10`?

**Comment by narcolepticinsomniac** [comment]
Searched issues, and this was the most closely related. I'm curious about start time URL parameters also. They don't work currently? I'm using a URL redirector to switch all requests, and I've got it working pretty well, but start time params are ignored. Wondering if my regex is off, or if it just isn't implemented yet.

Great project, btw. I was looking for a suitable Hooktube replacement, and this works pretty well so far.

**Comment by omarroth** [comment]
That's quite strange, it should support `t`, or `start` and `end`. Do you have an example URL?

For others as well: the format for time for each of the above parameters can be an integer number of seconds, or a time span matching the following format: `\d+h\d+m\d+s\d+ms`. They don't have to be in that order, and they can be in any order. Examples:


- `12h5m`
- `10ms10s`

Which should be compatible with any dates compatible with YouTube.

**Comment by omarroth** [comment]
That's quite strange, it should support `t`, `start`, and `end`. `t ` is synonymous with `start`. Do you have an example URL?

For others as well: the format for time for each of the above parameters can be an integer number of seconds, or a time span matching the following format: `\d+h\d+m\d+s\d+ms`. They don't have to be in that order, and ant can be ommitted. Examples:


- `12h5m`
- `10ms10s`

Which should be compatible with any dates compatible with YouTube.

**Comment by narcolepticinsomniac** [comment]
I guess it was kinda working, but the example I used wasn't obvious, because it always started at the beginning of the timeline. If a different start time is specified, the preceding timeline is just cut? For example:

https://invidio.us/embed/4NJlUribp3c?fs=1&autoplay=1&enablejsapi=1&start=60

Instead of jumping 60 secs in the timeline, the 60 secs is just gone, and a 4:06 min vid is now 3:06. Is this intentional? Seems like a really odd way of doing it. Sometimes you wanna go back for context.

**Comment by narcolepticinsomniac** [comment]
That's good news man, thanks.

**Comment by narcolepticinsomniac** [comment]
Not to be impatient, but this struck me as a fairly simple update, and nothing appears to have changed as of yet.

I also agree with the OP. Not necessarily just a "copy" button, but I don't see why you wouldn't provide download buttons in your html5 players.

**Comment by omarroth** [comment]
I would recommend opening that as a new issue if you would like it to be added. Adding a download button seems fairly unrelated to the original issue, which is adding a `share` button. 

To answer your question though: the reason there are no download buttons is mostly because that's the default for VideoJS and I haven't found a way to add them back. For now though if you want to download a video you can right-click > "save video as.." which should do what you want.

When #34 is closed a dedicated download button and/or dropdown for users to select their preferred source will likely be added, similar to [CloudTube](https://cadence.gq/cloudtube).

**Comment by narcolepticinsomniac** [comment]
>you can right-click > "save video as.."

Yeah, NBD really, just one click vs a few.

Download buttons were mostly an afterthought. Must've misunderstood the OP if they're off topic, but it seems like you've got a pretty good idea of the little features users want.

I'm mostly just curious when the switch to `videojs-offset` can be expected.

**Comment by omarroth** [comment]
Take a look at #55, which adds markers. It should be merged soon.
