### ISSUE TITLE
Sign in cookie for other domains

### ISSUE THREAD

**Issue by omar-elnaggar** [omarroth/invidious#391]
Set up a local instance of Invidious using the updater script. Logging in resulted in nothing happening. On further inspection the response cookie was for the .invidio.us domain. Editing the domain field on the cookie allowed me to sign in.

**Comment by omarroth** [comment]
Should be fixed with 17cf0772fb9ab483391942a33fec6e71aa25128d. Previously, the `domain` option in `config.yml` was `invidio.us`. It will now issue a cookie without a `domain` by default, which should fix the issue you're having.

See also #304 and the wiki page on [Configuration](https://github.com/omarroth/invidious/wiki/Configuration) for setting a cookie for a domain. RSS feeds and some other features require an absolute domain for some of the resources they link to.

**Comment by omar-elnaggar** [comment]
Updated and changed the `domain` option in the `config.yml` and I am able to sign in now with no issues. Thanks for the quick fix!
