### ISSUE TITLE
RSS feed does not take port into account

### ISSUE THREAD

**Issue by omar-elnaggar** [omarroth/invidious#395]
I use port `3000` still for my local instance of invidious and the `RSS` feed does not account for port number in the link. I used a workaround using the Redirector plugin for now.

https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd

**Comment by omarroth** [comment]
Should be fixed with 1435516.

**Comment by omar-elnaggar** [comment]
Fixed.

**Comment by Aquariu** [comment]
Dear all,

Sorry to post on this topic after a long slumber.

The RSS feed  created for my subsciption is wrong:
- instance is receiving requests on port 3001
- There's an nginx proxy (domain name, Let's encrypt cert ...) revieves requests on port 433 and 80 (and forwards 80 to  433)

But the RSS feeds provide links with port 3000  (that is domain.tld:3000/xxxxx)

I tried recompiling (with shards update && shards install && crystal build...)
To no avail.

I may have build & launched my instance on port 3000 the first time I tried switched to 3001 because I have another service listening on port 3000. 
But anyway, since I have a nginx reverse proxy I actually need to have the RSS feed links without port (default HTTPS requests on port 433).

Is it a database value somewhere ? a configuration setting that I can't see ?

Thanks for your help.
Regards

Olivier

**Comment by TheFrenchGhosty** [comment]
@Aquariu https://github.com/iv-org/invidious/issues/1363

**Comment by Aquariu** [comment]
Thanks for this, that was it. Discoverability of the configuration is a bit difficult.
Also, my search skills were obviously lacking. I found this thread but not the other one you linked to.

**Comment by TheFrenchGhosty** [comment]
@Aquariu Yeah, I'm planning on working a bit on the readme and this is one of the thing I will make sure to add.
