### ISSUE TITLE
Integrate DeArrow

### ISSUE THREAD

**Issue by pelag0s** [omarroth/invidious#4006]
**Is your feature request related to a problem? Please describe.**

Youtube is increasingly being ragged with clickbaity titles and thumbnails. Oftentimes, from the search results it is totally unclear what a video is about.

**Describe the solution you'd like**

There is an interesting project called [DeArrow](https://dearrow.ajay.app/) which replaces titles and subtitles with more descriptive, community-sourced alternatives.

Originally, it works as a browser extension. But the databases are open and downloadable, so they could be used in alternative clients like Invidious as well. There could be an option to enable or disable the alternative titles / subtitles in the interface (just as in the browser extension).

**Describe alternatives you've considered**

There is already [user scripts (and also an integration in piped)](https://github.com/ajayyy/DeArrow/issues/39) but it would be much nicer to have this integrated in Invidious.

**Comment by unixfox** [comment]
It makes more sense to have the extension integrated for invidious than us implementing this feature.

**Comment by unixfox** [comment]
@TheFrenchGhosty do we want to implement this feature into invidious? I feel like we prefer to avoid bloating the invidious core.

Just like the sponsor block extension.

**Comment by TheFrenchGhosty** [comment]
Hello, yes I can confirm what @unixfox said, Invidious should remain as lean as possible, which mean that Sponsorblock and DeArrow (and anything that interacts with YouTube using a browser addon) should support Invidious themselves.

There's really no point in implementing this ourselves, Invidious needs a browser to run, a browser support the addons. Where it makes sense is in applications like NewPipe where addons aren't possible.

I already asked @ajayyy what was planed for DeArrow, and from what I understood, he plans to add support for Invidious when DeArrow is more mature.

**Comment by djmaze** [comment]
Thanks, got it.

**Comment by TheFrenchGhosty** [comment]
@TatianaPink 


>There are more mobile Internet users than desktop users nowadays
>Sponsorblock isn't officially supported by any mobile browser, not even Firefox

Invidious isn't and was never made for mobile use. I specifically want it to focus on the desktop (without purposefully ruining the mobile use). The fact that it's usable on mobile is because "it can so why not", no dedicated feature will be implemented *just for mobile*. 

On mobile NewPipe is the thing you should be using, it's an old and reliable project from a trustworthy team. If you want something that uses Invidious, [Clipious](https://f-droid.org/packages/com.github.lamarios.clipious/) just came out and seems to do a good job (do note that I personally haven't used it much and I haven't checked how it works and how trustworthy the people around it are). Invidious will *always* be for desktop use first, and we will always recommend NewPipe as long as it is doing good.

>Sponsorblock makes connections to the developer's server. The developer claims that there's no privacy risk because it uses only the first characters in a video ID, but based on the number of views of the possible matches, he (and whoever hacks into his server) can still make good guesses of what videos each user is watching. Implementing Sponsorblock on the Invidious server-side would protect people's privacy for real

The Sponsorblock developer (@ajayyy ) is someone who have been doing FOSS for years, even before Sponsorblock started. He has been around Invidious for years, he is a trusted member. Moreover (unlike a certain add-on to add back the dislike) the database of both projects are open and downloadable. It's all FOSS, so if you don't trust him, you can host it yourself (and point the add-on to your own server, because yes, is possible [it's possible](https://github.com/iv-org/invidious/assets/47571719/9a63f6ef-f9fd-41cc-ac06-5186cd3c28a9)).

**Comment by NintendoManiac64** [comment]
I just want to be able to use this on Invidious in a browser that uses traditional XUL extensions rather than the "web extensions" of the Chromified web.

I mean, a big reason I'm using Invidious is because I use a browser that doesn't subscribe to the "theory of Chromification".

**Comment by NintendoManiac64** [comment]
Since my comment was minimized presumably as being off-topic in the other place I asked without it actually being given a reply, I guess I'll my question here instead...

Does the following change the situation at all in terms of considering whether to implement DeArrow support?:

- https://github.com/iv-org/invidious/pull/4985

(the situation with XUL-based browsers I mentioned above still has not changed)

**Comment by unixfox** [comment]
Locking the issue has the answer has already been given: https://github.com/iv-org/invidious/issues/4006#issuecomment-1654074559
