### ISSUE TITLE
Search engine doesn't find a video

### ISSUE THREAD

**Issue by halbaka** [omarroth/invidious#445]
I've looked for [this](https://www.youtube.com/watch?v=cBMR0YlUwBw) german video on invidio.us. 

The title is _Mayday - Alarm im Cockpit - S16E06 - Absturz in der Kälte_.
But I can't find it by using the search box. Variations, for example _Mayday Absturz in der Kälte_, don't work, too. However, the [direct link](https://www.invidio.us/watch?v=cBMR0YlUwBw) works.

**Comment by omarroth** [comment]
Since invidio.us is hosted in the US, the mentioned video likely isn't appearing in search because the video is region locked to Germany.

Forcing a region [manually](https://www.invidio.us/search?q=Mayday+-+Alarm+im+Cockpit+-+S16E06+-+Absturz+in+der+Kälte&region=DE) in search shows the mentioned video.

**Comment by halbaka** [comment]
I wasn't aware of this. Thanks!
