### ISSUE TITLE
RSS feed not valid?

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#509]
With ifttt, I would like to subscribe to invidious' Podcast RSS feed. But the feed content is not valid, according to: 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Finvidio.us%2Ffeed%2Fchannel%2FUC16niRr50-MSBwiO3YDb3RA

**Comment by omarroth** [comment]
Validator returns the same errors for the equivalent feed provided by YouTube: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUC16niRr50-MSBwiO3YDb3RA . If there are any issues that cause issues for readers feel free to mention them, otherwise the issue appears to be in the validator, rather than the feed provided by Invidious.

**Comment by gloschtla** [comment]
Interesting! 
ok, is there any alternative way to automatically post new invidious&listen=1 links into a telegram channel including content preview?

**Comment by gloschtla** [comment]
Within past hour, it seemed to work suddenly.

**Comment by omarroth** [comment]
I'm going to close this then, feel free to mention here or open a new issue if you encounter any issues with feeds.
