### ISSUE TITLE
Why does this Error always occure on this channel?

### ISSUE THREAD

**Issue by CSDUMMI** [omarroth/invidious#524]
One many of the videos on this channel give this error:

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

Why is that?
#
https://invidio.us/channel/UC3XTzVzaHQEd30rQbuvCtTQ

**Comment by omarroth** [comment]
From a quick look it appears most videos are blacklisted in Australia, Great Britain, New Zealand, Canada, or some combination. If you are in one of those regions  you will see that error if you don't have `Proxy videos?` enabled.

Testing a couple videos there doesn't appear to be any issue with playback for me. If adding `local=true` to the end of the `/watch` URL doesn't fix the issue for you, would you mind providing a specific example?

**Comment by CSDUMMI** [comment]
I think I have to give you more information:
If I mostly get this error, if I am watching a video on my phone:

iPhone
iOS 10.3.3
Firefox for iOS Verssion 14.0

But on my PC I can watch these videos without a problem.
Example:
https://www.invidio.us/watch?v=gmgV4r25XxA

By the way, it seems if I'm using Safari, the video loads again without a problem.

**Comment by avocadoras** [comment]
@omarroth I see this issue a lot on my end as well. Can confirm that adding `&local=true` after end of `/watch...` URL fixed it for me. I have only tried with one video though.

**Comment by oxxz** [comment]
@omarroth i also have had this issue since i started using invidious a couple of months ago. didnt really take a look on it until i found this issue. can also confirm that `&local=true` fixes it, at least for the one video i've tried so far. i cant really see any obvious pattern for which videos works and which wont, but its maybe 4/10 that doesnt work for me. i live in europe but none of the countries u mentioned.

**Comment by CSDUMMI** [comment]
And why does it occure?
And how can one fix it?
Should `&local=true` be default, because
I can't do that on every video on my mobile phone.

**Comment by Perflyst** [comment]
It is probably due to geoblocking from YouTube. You cannot fix it.

In settings (you can do this with out an account), enable "Proxy Videos?"

**Comment by CSDUMMI** [comment]
What exactly does "Proxy Videos?" do if it is enabled?

**Comment by CSDUMMI** [comment]
And why is there no option in settings for the `local` parameter?

**Comment by Perflyst** [comment]
Proxy Videos is the local parameter

**Comment by avocadoras** [comment]
@Perflyst do you mean [this](https://support.google.com/youtube/answer/6303378?hl=en)? I am able to view the video through the YouTube url, but I cannot view the same video through Invidio.

**Comment by Perflyst** [comment]
Look on issue #92

**Comment by avocadoras** [comment]
@Perflyst thanks. I'm unaware of how the Invidio interacts with Youtube to fetch the videos; however, I'm able to view the video when I click to open via the Youtube Link button.

**Comment by Perflyst** [comment]
Yeah, this can be the case. This should also be discussed somewhere in #92 
If you have specific furhter questions better join #invidious on freenode or #invidious:matrix.org, probably better than here.

**Comment by omarroth** [comment]
Sometimes video files will not play if they're being accessed from a different region than where the video was originally requested, even if the video itself is not region blocked.

Since https://invidio.us is hosted in the US, users outside that region will sometimes encounter errors when attempting to view videos. I think music videos most commonly encounter this issue.

`Proxy videos` or `&local=true` will attempt to load the file through Invidious, see [this explanation](https://github.com/omarroth/invidious/issues/453#issuecomment-477574597) for some more details on how it works. It's more resource intensive which is why it isn't enabled by default. You can also try using an [instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances) hosted in your region.

Closing in favor of #92.
