### ISSUE TITLE
Question: Is Account Data Encrypted?

### ISSUE THREAD

**Issue by trymeouteh** [omarroth/invidious#568]
Are users account data encrypted such as watch history, subscriptions, settings? Or is it stored in plain text?

And if not will this be added in the future to increase users privacy?

I understand some things cannot be encrypted such as the accounts RSS feed which should be disabled by default unless the user wants an RSS feed if encryption is added to accounts.

**Comment by omarroth** [comment]
Passwords are hashed with [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) before they're stored. Otherwise data is stored using the defaults provided by Postgres.

It's not planned and I currently don't think it's practical. For example, this query to provide notifications:

```
UPDATE users SET notifications = notifications || $1 \
      WHERE updated < $2 AND $3 = ANY(subscriptions) AND $1 <> ALL(notifications) RETURNING email
```

Requires `notifications`, `subscriptions`, `updated`,  `email` be accessible without action from the client. There are similar queries elsewhere used for pulling videos from subscribed channels, updating feeds, etc.

Maybe a more client-focused service could offer this, like [FreeTube](https://github.com/FreeTubeApp/FreeTube) or [CloudTube](https://cadence.moe/cloudtube/subscriptions), but I don't think it's currently possible for Invidious.

**Comment by trymeouteh** [comment]
Makes sense, passwords of course should be encrypted no matter what. The nice thing about this service is that no email is required allowing you to use have an anonymous account by having your username not identify you.
