### ISSUE TITLE
URL parameters do not work for embed videos (without cookie?)

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#588]
For example embeding a video always results in connections to googlevideo.com
I cannot set `https://invidio.us/embed/Bey4XXJAqS8&local=true`, the `local=true` automatically gets removed from the url.

It seems like the local=true only gets kept if the cookie for "Proxy videos = true" is set. But without a cookie in a new profile just opening `https://invidio.us/embed/Bey4XXJAqS8&local=true` results in removal of `local=true` and connections to google

**Comment by omarroth** [comment]
Looks like a typo, should be `https://invidio.us/embed/Bey4XXJAqS8?local=true`.

**Comment by Perflyst** [comment]
Seems to be, right....

**Comment by kniddl** [comment]
I encountered this issue as well but with autoplay=1. If I use a & in front the parameter is removed automatically and if I use a ? there is no effect. (Not as an embed works without an issue.)
I think this issue has to be reopened.

**Comment by omarroth** [comment]
The parameter is stripped from the end because it's considered part of the video ID. You can see this on YouTube when testing with e.g. https://www.youtube.com/embed/CvFH_6DNRCY&autoplay=1, which raises an error.

> autoplay=1 on its own works but in conjunction with controls=0 it does not.

I'm having trouble replicating this behavior. Testing with https://invidio.us/embed/CvFH_6DNRCY?autoplay=1&controls=0 appears to work as expected.

**Comment by kniddl** [comment]
I misunderstood how to add parameters. I thought each has to be preceded with a question mark but that does not make sense. Thanks for taking your time!
