### ISSUE TITLE
Outdated shard.lock (pg requirements changed). Please run shards update instead.

### ISSUE THREAD

**Issue by tleydxdy** [omarroth/invidious#591]
when running `docker-compose build`

**Comment by omarroth** [comment]
Should be fixed with 62f7f7a689ea08a8d680d221780d20def319b271.

**Comment by tleydxdy** [comment]
new error
```
Error in src/invidious.cr:1141: undefined method 'verify' for Crypto::Bcrypt::Password
      if Crypto::Bcrypt::Password.new(user.password.not_nil!).verify(password.byte_slice(0, 55))
```

**Comment by omarroth** [comment]
That's the issue I was referring to above with an outdated version. You'll want to make sure your base images are up-to-date using the instructions for updating in the [wiki](https://github.com/omarroth/invidious/wiki/Updating#with-docker).

**Comment by tleydxdy** [comment]
yep, this error comes up when using those commands

**Comment by atahanacar** [comment]
I get this error when trying to update using the instructions in the wiki.

`Error in src/invidious.cr:1159: undefined method 'verify' for Crypto::Bcrypt::Password

      if Crypto::Bcrypt::Password.new(user.password.not_nil!).verify(password.byte_slice(0, 55))
                                                              ^~~~~~

Rerun with --error-trace to show a complete error trace.
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c sed -i 's/host: localhost/host: postgres/' config/config.yml &&     shards update && shards install &&     crystal build src/invidious.cr' returned a non-zero code: 1
`

**Comment by atahanacar** [comment]
Found a workaround. First, I had to start a bash shell inside the docker container.
`docker exec -it invidious_invidious_1 bash`
Then, I updated the required packages
`pacman -Sy shards crystal imagemagick librsvg which pkgconf gcc ttf-liberation glibc`
Stashed the changes (because of my custom config), pulled and unstashed them.
`git stash && git pull && git stash pop`
Finally, built the updated version.
`crystal build src/invidious.cr`
After all these steps, restarted the docker container and everything was forking fine. I guess the main problem was with the git part. I am a noob when it comes to docker so I have no clue.

**Comment by leonklingele** [comment]
This should be fixed now that #665 is merged.

**Comment by atahanacar** [comment]
I've used the method I've previously mentioned to update to the latest commit. I'll test it once the a commit arrives.

**Comment by atahanacar** [comment]
Update: It works as expected now.

**Comment by omarroth** [comment]
I'd like to confirm the issue is fixed for @tleydxdy as well before closing this

**Comment by tleydxdy** [comment]
yep it works! and glad that build doesn't take nearly as much ram now.
