### ISSUE TITLE
closed stream on some instances

### ISSUE THREAD

**Issue by R0sinenb0mb3r** [omarroth/invidious#600]
Works:
https://de.invidious.snopyta.org/watch?v=h1wtfcX-GHM

didn't work:
https://fi.invidious.snopyta.org/watch?v=h1wtfcX-GHM

Is this some kind of censorship?
Then please mark the instances in your list.

Just search f.e. for Bannon and try to watch a stream on fi.invidious.snopyta.org - always 'closed stream'. Not very democratic...

I ask, because I often switch instances due to network latency. But I want to know which, I have to skip. THX.

**Comment by omarroth** [comment]
> Is this some kind of censorship?

No. `Closed stream` indicates some form of network error when attempting to access YouTube.

Attempting to view any video on https://fi.invidious.snopyta.org returns the same error, have you encountered this on any other instances?

Comparing stats between [`fi`](https://fi.invidious.snopyta.org/api/v1/stats?pretty=1) and [`de`](https://de.invidious.snopyta.org/api/v1/stats?pretty=1), `fi` appears slightly out-of-date, but otherwise don't see anything that might be causing the issue.

**Comment by Perflyst** [comment]
Just FYI @R0sinenb0mb3r fi.invidious.snopyta.org works again. We'll monitor it and try to find the issue. There is no kind of censorship on the instance itself done.

**Comment by omarroth** [comment]
Should be fixed with 5fd3ed782f5577b685e7de79a8bdf551dc64e13b.
