### ISSUE TITLE
Subscriptions don't show

### ISSUE THREAD

**Issue by zeyolerasi** [omarroth/invidious#625]
My subscriptions aren't showing. The settings I'm using are below. If I tick "Only show notifications", then when new videos are uploaded I get the new videos when clicking Subscriptions, but as soon as i leave the page, all the videos clear. If I untick only show unwatched, this doesn't seem to change the behaviour.

It feels like new videos from those channels are being flagged and should be in the list, but because there is no setting to "keep" those videos in, they are being marked as "user doesn't want the notifications, don't add to list".

Ideally if a user unticks all of these boxes, even watched videos would come back.

FF 67.0.4 . Logged in. I have javascript enabled, do use ublock but doesn't seem to be the issue.

I'd like to see all the videos from channels I'm subscribed to here. 
![agdhtre](https://user-images.githubusercontent.com/52600861/60756204-b212f680-9ff2-11e9-83e4-f6ded7218261.JPG)

**Comment by omarroth** [comment]
Would you mind providing your user ID? If you don't feel comfortable providing it here, you can send it privately to omarroth@protonmail.com. I'm assuming you're using https://invidio.us.

> I get the new videos when clicking Subscriptions, but as soon as i leave the page, all the videos clear.

I'm assuming this means you're subscription page appears empty after a refresh, but please correct me if I'm wrong here. A screenshot of your subscription page would also be helpful.

I've changed the title to "Subscriptions don't show", since that appears to be what you're describing. Please feel free to change it back if I'm misunderstanding the issue.

**Comment by hellomcbug** [comment]
When I first imported the subscriptions I noticed it took a while to show up. In general the subs page seems to have a delay in updating when compared to YT, which could be your issue.

**Comment by omarroth** [comment]
Should be fixed with 99b0b4f5b8d912afe62e88301628ffc7540c5f83.
