### ISSUE TITLE
Issue when trying to view the comments of a video

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#64]
When using Pale Moon to view them, they never load. In the Error Console, I am getting the following error:

Timestamp: 8/2/2018 6:47:36 PM
Error: ReferenceError: fetch is not defined
Source File: https://www.invidio.us/watch?v=vUdBNJ5eykk
Line: 289

**Comment by veloute** [comment]
Are you using any add-ons that could be interfering (e.g. NoScript, uMatrix, uBlock Origin (medium mode)?

**Comment by veloute** [comment]
If you do have any of them, ensure they aren't blocking unpkg.com.

**Comment by omarroth** [comment]
It seems to me that the issue is Pale Moon not supporting the Fetch API, which is used for getting comments. The best info I can find is [this](https://github.com/MoonchildProductions/Pale-Moon/issues/1385), which would suggest it is disabled by default, but it may have changed since September of last year.

Currently the Fetch API is supported by [most major browsers](https://github.com/MoonchildProductions/Pale-Moon/issues/1385) (including Firefox, on which Pale Moon is based). I may switch to using XMLHTTPRequests for compatibility with older browsers, otherwise I wouldn't expect this to be fixed soon.

**Comment by omarroth** [comment]
Going to `about:config` and checking `dom.fetch.enabled` appears to fix the issue.

**Comment by Zero3K** [comment]
Changing that value from false to true fixed it. Still, it makes sense to do what you mentioned so all browsers can view the comments of a video being shown on Invidious.

**Comment by omarroth** [comment]
Switched to XHR with 0685d3c7c292477e4911d617038bb08389d2a9ef.
