### ISSUE TITLE
Questions regarding comments

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#68]
1. Is it possible to reply to them?
2. Is it possible to like them?

**Comment by omarroth** [comment]
It is not possible to reply or like comments, mainly because it requires a Google account. I wouldn't expect either of these to be added, as it would require adding Google-only features. 

I think I'll add a "view comments on YouTube" similar to with Reddit comments so that it is possible to reply and like comments on the official website.

**Comment by Zero3K** [comment]
Adding that is fine by me.

**Comment by omarroth** [comment]
Added with 9fd0a02f1682ce95dce60c5bd7523af47f14397e. :)

**Comment by Zero3K** [comment]
Its too bad Youtube doesn't have a page with only the comments being shown.

**Comment by omarroth** [comment]
It is. Attempting to link directly to the comment section (`/watch?v=id:#comments`) doesn't work either.
