### ISSUE TITLE
Show time/date published under video in search

### ISSUE THREAD

**Issue by FredrikAugust** [omarroth/invidious#75]
Title pretty much says it all :) Should be pretty easy to change this in `components/video`, but I don't know the model of `video`, nor where I can check it, so I couldn't do it myself :)

**Comment by omarroth** [comment]
Added in 3dcb6766fc2d2d33565439323ba137bccd852069, but I'd like to make a note here:

Currently YouTube does not provide an accurate date for videos in search or on the front page, usually something like "5 weeks ago". So that's as precise as Invidious provides as well to avoid being misleading.

If you'd like to add any other information, you can find the model for `Video` [here](https://github.com/omarroth/invidious/blob/master/src/invidious/helpers.cr#L77-L106) :)

**Comment by FredrikAugust** [comment]
Wonderful! Good job :)

**Comment by FredrikAugust** [comment]
I must ask though, have you considered splitting that monstrous file into separate files? Would make navigation a bit easier.

**Comment by omarroth** [comment]
Not a bad idea, ha ha. I'm planning on doing some other refactoring as well soon.

**Comment by FredrikAugust** [comment]
Sounds like a good idea :) :+1:
