### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported. 

### ISSUE THREAD

**Issue by glaucocustodio** [omarroth/invidious#801]
Hi guys, I am in Portugal and when I try to access https://invidio.us/watch?v=bevGiTolFqI I get the message `The media could not be loaded, either because the server or network failed or because the format is not supported.` (I've tried on Firefox Developer Edition 70.0b and in Brave 0.68.132 Chromium: 76.0.3809.132).

I am only able to watch it by appending `&quality=dash`.

Any thoughts? Thanks.

**Comment by Booteille** [comment]
Hi.

You're probably using a Third-Party blocker as uMatrix.
By default, Invidious does not proxy the video through its servers (local=true, or quality=dash).
So, if you're not using this option, you'll make requests to the media file, located on googlevideos.com.

If you don't want to use the proxy, you'll have to allow medias from googlevideos.com.
Otherwise, just select `use proxy` or set quality to `dash` in params.

You can also check for extensions doing this by default if you don't want to use cookies on your Invidious instance.

Finally, if you plan to use the proxy. Think about switching to another instance than the official one. Because this feature uses a lot of bandwith.

**Comment by omarroth** [comment]
Closing in favor of #92. Also see [this](https://github.com/omarroth/invidious/wiki/Geoblocking,-available-video-quality-and-DASH) page in the wiki.
