### ISSUE TITLE
Feature request: Password recovery

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#838]
Hello,

If i forget my password, my account is lost forever since there's no way to recover it.

**Comment by TheFrenchGhosty** [comment]
Password recovery is a major security risk and a introduction of a massive point of failure in accounts security.

Some people hate it and I'm one of them, Tutanota.com (the email provider) for example enforced it and people hated it (See [this](https://redd.it/a3cw2u), [this](https://redd.it/9xx8bb) and [this](https://redd.it/al2ps5)) and they were using the most privacy-conscious way possible (recovery code) but the problem is that it was not the most security-conscious way.

If it's implemented in Invidious it needs to be optional while still being privacy-conscious enough... but also need to be security-conscious.

I sadly don't see any way to implement it correctly.

Password managers were created for a reason.

**Comment by omarroth** [comment]
Duplicate of #108.
