### ISSUE TITLE
Hello i write you emailomarroth

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#859]
Hello i write you email adress please reply me omarroth 

omarroth@proton***l.com

**Comment by omarroth** [comment]
As I've already mentioned in #840, #844, #852, and #858 if your IP has been banned it will not be possible to view videos through Invidious, see #811. Using `force_resolve: ipv6` will *only* work if you have an IPv6 address that has not been banned. Otherwise, you will have to wait for Google to unban you or get a new IP.

Any more of these issues created in future will be closed without comment.
