### ISSUE TITLE
add support for ipfs between the front end gates, to relieve backstorge and reduce used bandwith

### ISSUE THREAD

**Issue by KonoromiHimaries** [omarroth/invidious#899]
https://github.com/ipfs/go-ipfs#readme

**Comment by elypter** [comment]
invidio.us is mainly a frontend. its probably a better strategy to interface sites like peertube. they already have the implementation and infrastructure.

**Comment by KonoromiHimaries** [comment]
@elypter i don't think about decentralise site, but some popular video.. youtube give a ban, for uses so more bandwith and this is a solution for fix that.

**Comment by elypter** [comment]
i know but those sites would be better suited to mirror frequently used videos. besides, its mostly the metadata request that is causing the blocks. that could be mitigated by caching metadata. that could already save the majority of the requests. there is however probably no point in hosting that on a p2p service because of the latency. it wouldnt be a problem with the video source but metadata needs to be available quickly. i dont know how fast ipfs is in real time but i doubt it could compete with local storage or a dedicated server nearby.

**Comment by KonoromiHimaries** [comment]
@elypter would better than nothing. it's fast, try it on `https://bit.tube/dashboard`

**Comment by omarroth** [comment]
As far as I am aware, IPFS is used mainly for storage. Invidious does *not* store videos, so I don't expect this would provide much benefit. I think this is out of scope for the project.

**Comment by M09NST3R** [comment]
Can this be reconsidered, now that IPFS is widely used to host websites and has much better performance? Everything that helps us decentralize also helps us harder censorship resistance.

**Comment by Perflyst** [comment]
Invidious still does not store videos and definitely shouldn't store videos in the future either due to copyright laws.

**Comment by M09NST3R** [comment]
> Invidious still does not store videos and definitely shouldn't store videos in the future either due to copyright laws.

I don't suggest hosting the videos. IPFS is used for normal website hosting these days.

**Comment by M09NST3R** [comment]
(Maybe there are no code changes required at all ... I came here because I was trying to locate an Invidious instance that's hosted on IPFS, but couldn't find any, which surprised me a lot.)
